# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= Rails.application.credentials.database_username %>
  password: <%= Rails.application.credentials.database_password %>

development:
  <<: *default
  database: blog_on_rails_7_development

test:
  <<: *default
  database: blog_on_rails_7_test

production:
  <<: *default
  database: blog_on_rails_7_production
  username: blog_on_rails_7
  password: <%= ENV["BLOG_ON_RAILS_7_DATABASE_PASSWORD"] %>
